#!/bin/sh
#
# Author 2018 Zhenxing Xu <xuzhenxing@canaan-creative.com>
#
# Judging if there is a new MM firmware.
# If you have a new MM firmware version, it will download MM firmware version.
#
# Timeout command in /bin/bash
# timeout 300 wget https://canaan.io/downloads/software/${avalon_type}/mm/latest/MM${type}.mcs -P /tmp/
# timeout 300 wget https://canaan.io/downloads/software/${avalon_type}/mm/latest/md5sums -P /tmp/
#

[ ! -e /usr/bin/change_mm_version ] && exit

# Download changelog file
dl_changelog() {
    flag=0
    timer=60

    while [ "${timer}" -gt 0 ]
    do
        if [ "${flag}" -eq 0 ]; then
            flag=1
            wget -S https://canaan.io/downloads/software/$1/mm/latest/changelog -P ./ 2>change &
        fi
        md=`cat change | grep '100\%' | sed 's/\ /\n/g' | grep '100\%'`
        if [ "${md}" = "100%" ]; then
            break
        fi
        sleep 1
        timer=`expr ${timer} - 1`
    done
}

# Download mm file
dl_mm() {
    flag=0
    timer=180

    while [ "${timer}" -gt 0 ]
    do
	if [ "${flag}" -eq 0 ]; then
	    flag=1
	    wget -S https://canaan.io/downloads/software/$1/mm/latest/MM$2.mcs -P /tmp/ 2>/usr/bin/mm.log &
	fi
	mm=`cat /usr/bin/mm.log | grep '100\%' | sed 's/\ /\n/g' | grep '100\%'`
	if [ "${mm}" = "100%" ]; then
	    break
	fi
	sleep 1
	timer=`expr ${timer} - 1`
    done
}

# Download md5sums file
dl_md5sums() {
    flag=0
    timer=60

    while [ "${timer}" -gt 0 ]
    do
        if [ "${flag}" -eq 0 ]; then
            flag=1
            wget -S https://canaan.io/downloads/software/$1/mm/latest/md5sums -P /tmp/ 2>/usr/bin/md5sums.log &
        fi
        md=`cat /usr/bin/md5sums.log | grep '100\%' | sed 's/\ /\n/g' | grep '100\%'`
        if [ "${md}" = "100%" ]; then
            break
        fi
        sleep 1
        timer=`expr ${timer} - 1`
    done
}

# Checking if it need update mm version
for tmp in `cgminer-api estats | sed 's/DNA/\nDNA/g' | sed 's/\=Ver/\n\=Ver/g' | grep '\=Ver' | sed 's/\=Ver\[//g' | sed 's/\]//g'`
do
    type=`echo ${tmp} | cut -b 1-3`
    if [ ${type} == '821' ]; then
        avalon_type=avalon821
    elif [ ${type} == '831' ]; then
        avalon_type=avalon831
    elif [ ${type} == '841' ]; then
        avalon_type=avalon841
    elif [ ${type} == '851' ]; then
        avalon_type=avalon851
    else
        continue
    fi

    # Handle changlog file
    dl_changelog
    remote=`cat changelog | grep 'Version' | awk '{ print $2 }'`
    # Compare MM version
    if [ ${tmp} != ${remote} ]; then
        rm changelog
        echo "1" >> change_mm_version
    fi

    # Download mm and md5sums files
    dl_mm ${avalon_type} ${type}
    dl_md5sums ${avalon_type}

    # MD5sum compare and upgrade mm firmware
    cd /tmp
    ck_mm=`md5sum MM${type}.mcs`
    ck_md5=`cat md5sums | grep 'mcs'`
    if [ "$ck_mm" = "$ck_md5" ]; then
        mv MM${type}.mcs mm.mcs
        rm md5sums
    else
        rm -f MM${type}.mcs md5sums
    fi
done
